[package]
name = "flagship"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = "0.99.18"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
thiserror = "1.0.63"

[dev-dependencies]
anyhow = "1.0.86"
